### ISSUE TITLE
Error that keeps crashing Coursity

### ISSUE THREAD

**Issue by AbeOmor** [sarmadhashmi/Coursity#60]
For forever logs.
info: Getting parser for mcmaster
/root/master/parsers/mcmaster.js:131
                    'course_number' : currentSection[1] ? currentSection[1] :
                                                    ^
TypeError: Cannot read property '1' of null
    at Object.parse (/root/master/parsers/mcmaster.js:131:53)
    at /root/master/app.js:145:32
    at fn (/root/master/node_modules/async/lib/async.js:746:34)
    at /root/master/node_modules/async/lib/async.js:1213:16
    at /root/master/node_modules/async/lib/async.js:166:37
    at /root/master/node_modules/async/lib/async.js:706:43
    at /root/master/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/root/master/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
error: Forever detected script exited with code: 1
error: Script restart attempt #122

**Comment by AbeOmor** [comment]
Added #59 as a temporary fix. Should add a way to track error calendars. If there is a calendar that causes an error, the raw data should be sent to the log file. @sarmadhashmi How do we add this?
